package in.yumtum.api.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Betausers was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Betausers extends CayenneDataObject {

    public static final String EMAIL_PROPERTY = "email";
    public static final String REG_DATE_PROPERTY = "regDate";
    public static final String REG_ID_PROPERTY = "regID";
    public static final String SREF_ID_PROPERTY = "srefId";
    public static final String UREF_ID_PROPERTY = "urefId";

    public static final String REG_ID_PK_COLUMN = "regID";

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setRegDate(Date regDate) {
        writeProperty("regDate", regDate);
    }
    public Date getRegDate() {
        return (Date)readProperty("regDate");
    }

    public void setRegID(Integer regID) {
        writeProperty("regID", regID);
    }
    public Integer getRegID() {
        return (Integer)readProperty("regID");
    }

    public void setSrefId(String srefId) {
        writeProperty("srefId", srefId);
    }
    public String getSrefId() {
        return (String)readProperty("srefId");
    }

    public void setUrefId(String urefId) {
        writeProperty("urefId", urefId);
    }
    public String getUrefId() {
        return (String)readProperty("urefId");
    }

}
