package in.yumtum.api.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import in.yumtum.api.cayenne.persistent.YtRestTimings;

/**
 * Class _YtRestBooking was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _YtRestBooking extends CayenneDataObject {

    public static final String BOOKING_ID_PROPERTY = "bookingId";
    public static final String BOOKING_SOURCE_ID_PROPERTY = "bookingSourceId";
    public static final String BOOKING_TIME_PROPERTY = "bookingTime";
    public static final String BOOKING_USER_ID_PROPERTY = "bookingUserId";
    public static final String NO_OF_PEOPLE_PROPERTY = "noOfPeople";
    public static final String RESERVE_DATE_PROPERTY = "reserveDate";
    public static final String REST_ID_PROPERTY = "restId";
    public static final String TO_YT_REST_TIMINGS_PROPERTY = "toYtRestTimings";

    public static final String BOOKING_ID_PK_COLUMN = "booking_id";

    public void setBookingId(Integer bookingId) {
        writeProperty("bookingId", bookingId);
    }
    public Integer getBookingId() {
        return (Integer)readProperty("bookingId");
    }

    public void setBookingSourceId(String bookingSourceId) {
        writeProperty("bookingSourceId", bookingSourceId);
    }
    public String getBookingSourceId() {
        return (String)readProperty("bookingSourceId");
    }

    public void setBookingTime(Date bookingTime) {
        writeProperty("bookingTime", bookingTime);
    }
    public Date getBookingTime() {
        return (Date)readProperty("bookingTime");
    }

    public void setBookingUserId(Integer bookingUserId) {
        writeProperty("bookingUserId", bookingUserId);
    }
    public Integer getBookingUserId() {
        return (Integer)readProperty("bookingUserId");
    }

    public void setNoOfPeople(String noOfPeople) {
        writeProperty("noOfPeople", noOfPeople);
    }
    public String getNoOfPeople() {
        return (String)readProperty("noOfPeople");
    }

    public void setReserveDate(Date reserveDate) {
        writeProperty("reserveDate", reserveDate);
    }
    public Date getReserveDate() {
        return (Date)readProperty("reserveDate");
    }

    public void setRestId(Integer restId) {
        writeProperty("restId", restId);
    }
    public Integer getRestId() {
        return (Integer)readProperty("restId");
    }

    public void setToYtRestTimings(YtRestTimings toYtRestTimings) {
        setToOneTarget("toYtRestTimings", toYtRestTimings, true);
    }

    public YtRestTimings getToYtRestTimings() {
        return (YtRestTimings)readProperty("toYtRestTimings");
    }


}
