package in.yumtum.api.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import in.yumtum.api.cayenne.persistent.YtRestTimings;
import in.yumtum.api.cayenne.persistent.YtRestUser;

/**
 * Class _YtRestaurants was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _YtRestaurants extends CayenneDataObject {

    public static final String ACCEPT_CC_PROPERTY = "acceptCC";
    public static final String ACTIVE_PROPERTY = "active";
    public static final String ADDRESS_PROPERTY = "address";
    public static final String AVG_COST_FOR_TWO_PROPERTY = "avgCostForTwo";
    public static final String CITY_PROPERTY = "city";
    public static final String CUSINES_PROPERTY = "cusines";
    public static final String HAS_AC_PROPERTY = "hasAC";
    public static final String HAS_WIFI_PROPERTY = "hasWifi";
    public static final String IS_VEG_PROPERTY = "isVeg";
    public static final String LATITUDE_PROPERTY = "latitude";
    public static final String LOCALITY_PROPERTY = "locality";
    public static final String LONGITUDE_PROPERTY = "longitude";
    public static final String NAME_PROPERTY = "name";
    public static final String NFS_PHONE_PROPERTY = "nfsPhone";
    public static final String PHONES_PROPERTY = "phones";
    public static final String REST_ID_PROPERTY = "restId";
    public static final String TO_YT_REST_USER_PROPERTY = "toYtRestUser";
    public static final String YT_REST_TIMINGS_ARRAY_PROPERTY = "ytRestTimingsArray";

    public static final String REST_ID_PK_COLUMN = "rest_id";

    public void setAcceptCC(Integer acceptCC) {
        writeProperty("acceptCC", acceptCC);
    }
    public Integer getAcceptCC() {
        return (Integer)readProperty("acceptCC");
    }

    public void setActive(Integer active) {
        writeProperty("active", active);
    }
    public Integer getActive() {
        return (Integer)readProperty("active");
    }

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }

    public void setAvgCostForTwo(Integer avgCostForTwo) {
        writeProperty("avgCostForTwo", avgCostForTwo);
    }
    public Integer getAvgCostForTwo() {
        return (Integer)readProperty("avgCostForTwo");
    }

    public void setCity(String city) {
        writeProperty("city", city);
    }
    public String getCity() {
        return (String)readProperty("city");
    }

    public void setCusines(String cusines) {
        writeProperty("cusines", cusines);
    }
    public String getCusines() {
        return (String)readProperty("cusines");
    }

    public void setHasAC(Integer hasAC) {
        writeProperty("hasAC", hasAC);
    }
    public Integer getHasAC() {
        return (Integer)readProperty("hasAC");
    }

    public void setHasWifi(Integer hasWifi) {
        writeProperty("hasWifi", hasWifi);
    }
    public Integer getHasWifi() {
        return (Integer)readProperty("hasWifi");
    }

    public void setIsVeg(Integer isVeg) {
        writeProperty("isVeg", isVeg);
    }
    public Integer getIsVeg() {
        return (Integer)readProperty("isVeg");
    }

    public void setLatitude(String latitude) {
        writeProperty("latitude", latitude);
    }
    public String getLatitude() {
        return (String)readProperty("latitude");
    }

    public void setLocality(String locality) {
        writeProperty("locality", locality);
    }
    public String getLocality() {
        return (String)readProperty("locality");
    }

    public void setLongitude(String longitude) {
        writeProperty("longitude", longitude);
    }
    public String getLongitude() {
        return (String)readProperty("longitude");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setNfsPhone(String nfsPhone) {
        writeProperty("nfsPhone", nfsPhone);
    }
    public String getNfsPhone() {
        return (String)readProperty("nfsPhone");
    }

    public void setPhones(String phones) {
        writeProperty("phones", phones);
    }
    public String getPhones() {
        return (String)readProperty("phones");
    }

    public void setRestId(Integer restId) {
        writeProperty("restId", restId);
    }
    public Integer getRestId() {
        return (Integer)readProperty("restId");
    }

    public void setToYtRestUser(YtRestUser toYtRestUser) {
        setToOneTarget("toYtRestUser", toYtRestUser, true);
    }

    public YtRestUser getToYtRestUser() {
        return (YtRestUser)readProperty("toYtRestUser");
    }


    public void addToYtRestTimingsArray(YtRestTimings obj) {
        addToManyTarget("ytRestTimingsArray", obj, true);
    }
    public void removeFromYtRestTimingsArray(YtRestTimings obj) {
        removeToManyTarget("ytRestTimingsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<YtRestTimings> getYtRestTimingsArray() {
        return (List<YtRestTimings>)readProperty("ytRestTimingsArray");
    }


}
